### ISSUE TITLE
不说是开源的吗？

### ISSUE THREAD

**Issue by lion117** [lc-soft/PunchAndKick#1]
看到自己陪伴自己童年的游戏 竟然可以自行定制的时候，内心当中的兴奋值瞬间爆表。 对当年虐电脑 屡试不爽。
但是进入github 之后却发现之后一个 readme 。心突然凉了一半，同志，不是说好开源的吗？

**Comment by lc-soft** [comment]
请切换分支，点击那个 branch:master 按钮即可。
当前默认分支是 master，老版本的代码在 early-demo 分支上。
