### ISSUE TITLE
退出的时候报错：Couldn't release mutex

### ISSUE THREAD

**Issue by triton-lwy** [lc-soft/PunchAndKick#2]
退出的时候报错：Couldn't release mutex
另外，求LCUI库的版本号和源码~ 下载了LC-Team/LCUI，发现版本不一致
@lc-soft

**Comment by lc-soft** [comment]
版本是 0.15.0：https://github.com/LC-Team/LCUI/releases/tag/v0.15.0

这个项目暂时不维护了。

**Comment by triton-lwy** [comment]
thx
